import { cssVar } from '../utils/cssVar.js'

export const themeTokens = {
    palette: {
        primary: {
            50: cssVar('palette.primary.50'),
            100: cssVar('palette.primary.100'),
            200: cssVar('palette.primary.200'),
            300: cssVar('palette.primary.300'),
            400: cssVar('palette.primary.400'),
            500: cssVar('palette.primary.500'),
            600: cssVar('palette.primary.600'),
            700: cssVar('palette.primary.700'),
            800: cssVar('palette.primary.800'),
            900: cssVar('palette.primary.900'),
        },
        neutral: {
            50: cssVar('palette.neutral.50'),
            100: cssVar('palette.neutral.100'),
            200: cssVar('palette.neutral.200'),
            300: cssVar('palette.neutral.300'),
            400: cssVar('palette.neutral.400'),
            500: cssVar('palette.neutral.500'),
            600: cssVar('palette.neutral.600'),
            700: cssVar('palette.neutral.700'),
            800: cssVar('palette.neutral.800'),
            900: cssVar('palette.neutral.900'),
        },
    },
    color: {
        background: {
            page: cssVar('color.background.page'),
            panel: cssVar('color.background.panel'),
            card: cssVar('color.background.card'),
            overlay: cssVar('color.background.overlay'),
            inset: cssVar('color.background.inset'),
            muted: cssVar('color.background.muted'),
        },
        foreground: {
            primary: cssVar('color.foreground.primary'),
            secondary: cssVar('color.foreground.secondary'),
            tertiary: cssVar('color.foreground.tertiary'),
            muted: cssVar('color.foreground.muted'),
            onAccent: cssVar('color.foreground.onAccent'),
        },
        border: {
            subtle: cssVar('color.border.subtle'),
            default: cssVar('color.border.default'),
            strong: cssVar('color.border.strong'),
        },
        accent: {
            background: cssVar('color.accent.background'),
            color: cssVar('color.accent.color'),
            border: cssVar('color.accent.border'),
            shadow: cssVar('color.accent.shadow'),
            hoverBackground: cssVar('color.accent.hoverBackground'),
            activeBackground: cssVar('color.accent.activeBackground'),
        },
        state: {
            success: cssVar('color.state.success'),
            warning: cssVar('color.state.warning'),
            danger: cssVar('color.state.danger'),
            info: cssVar('color.state.info'),
            disabled: cssVar('color.state.disabled'),
        },
    },
    surface: {
        page: {
            background: cssVar('surface.page.background'),
            backdropFilter: cssVar('surface.page.backdrop-filter'),
            border: cssVar('surface.page.border'),
            radius: cssVar('surface.page.radius'),
            shadow: cssVar('surface.page.shadow'),
            color: cssVar('surface.page.color'),
        },
        panel: {
            background: cssVar('surface.panel.background'),
            backdropFilter: cssVar('surface.panel.backdrop-filter'),
            border: cssVar('surface.panel.border'),
            radius: cssVar('surface.panel.radius'),
            shadow: cssVar('surface.panel.shadow'),
            color: cssVar('surface.panel.color'),
        },
        card: {
            background: cssVar('surface.card.background'),
            backdropFilter: cssVar('surface.card.backdrop-filter'),
            border: cssVar('surface.card.border'),
            radius: cssVar('surface.card.radius'),
            shadow: cssVar('surface.card.shadow'),
            color: cssVar('surface.card.color'),
        },
        overlay: {
            background: cssVar('surface.overlay.background'),
            backdropFilter: cssVar('surface.overlay.backdrop-filter'),
            border: cssVar('surface.overlay.border'),
            radius: cssVar('surface.overlay.radius'),
            shadow: cssVar('surface.overlay.shadow'),
            color: cssVar('surface.overlay.color'),
        },
        inset: {
            background: cssVar('surface.inset.background'),
            backdropFilter: cssVar('surface.inset.backdrop-filter'),
            border: cssVar('surface.inset.border'),
            radius: cssVar('surface.inset.radius'),
            shadow: cssVar('surface.inset.shadow'),
            color: cssVar('surface.inset.color'),
        },
    },
    radius: {
        none: cssVar('radius.none'),
        xs: cssVar('radius.xs'),
        sm: cssVar('radius.sm'),
        md: cssVar('radius.md'),
        lg: cssVar('radius.lg'),
        xl: cssVar('radius.xl'),
        '2xl': cssVar('radius.2xl'),
        '3xl': cssVar('radius.3xl'),
        full: cssVar('radius.full'),
    },
    shadow: {
        none: cssVar('shadow.none'),
        xs: cssVar('shadow.xs'),
        sm: cssVar('shadow.sm'),
        md: cssVar('shadow.md'),
        lg: cssVar('shadow.lg'),
        xl: cssVar('shadow.xl'),
        '2xl': cssVar('shadow.2xl'),
        inner: cssVar('shadow.inner'),
        glow: cssVar('shadow.glow'),
    },
    spacing: {
        0: cssVar('spacing.0'),
        1: cssVar('spacing.1'),
        2: cssVar('spacing.2'),
        3: cssVar('spacing.3'),
        4: cssVar('spacing.4'),
        5: cssVar('spacing.5'),
        6: cssVar('spacing.6'),
        8: cssVar('spacing.8'),
        10: cssVar('spacing.10'),
        12: cssVar('spacing.12'),
        16: cssVar('spacing.16'),
        20: cssVar('spacing.20'),
        24: cssVar('spacing.24'),
        32: cssVar('spacing.32'),
    },
    typography: {
        fontFamily: {
            sans: cssVar('typography.fontFamily.sans'),
            serif: cssVar('typography.fontFamily.serif'),
            mono: cssVar('typography.fontFamily.mono'),
            display: cssVar('typography.fontFamily.display'),
        },
        fontSize: {
            xs: cssVar('typography.fontSize.xs'),
            sm: cssVar('typography.fontSize.sm'),
            md: cssVar('typography.fontSize.md'),
            lg: cssVar('typography.fontSize.lg'),
            xl: cssVar('typography.fontSize.xl'),
            '2xl': cssVar('typography.fontSize.2xl'),
            '3xl': cssVar('typography.fontSize.3xl'),
            '4xl': cssVar('typography.fontSize.4xl'),
            '5xl': cssVar('typography.fontSize.5xl'),
        },
        fontWeight: {
            regular: cssVar('typography.fontWeight.regular'),
            medium: cssVar('typography.fontWeight.medium'),
            semibold: cssVar('typography.fontWeight.semibold'),
            bold: cssVar('typography.fontWeight.bold'),
            black: cssVar('typography.fontWeight.black'),
        },
        lineHeight: {
            tight: cssVar('typography.lineHeight.tight'),
            normal: cssVar('typography.lineHeight.normal'),
            relaxed: cssVar('typography.lineHeight.relaxed'),
        },
        letterSpacing: {
            tight: cssVar('typography.letterSpacing.tight'),
            normal: cssVar('typography.letterSpacing.normal'),
            wide: cssVar('typography.letterSpacing.wide'),
        },
    },
    motion: {
        duration: {
            instant: cssVar('motion.duration.instant'),
            fast: cssVar('motion.duration.fast'),
            normal: cssVar('motion.duration.normal'),
            slow: cssVar('motion.duration.slow'),
            slower: cssVar('motion.duration.slower'),
        },
        easing: {
            linear: cssVar('motion.easing.linear'),
            easeIn: cssVar('motion.easing.easeIn'),
            easeOut: cssVar('motion.easing.easeOut'),
            easeInOut: cssVar('motion.easing.easeInOut'),
            spring: cssVar('motion.easing.spring'),
        },
    },
    blur: {
        none: cssVar('blur.none'),
        xs: cssVar('blur.xs'),
        sm: cssVar('blur.sm'),
        md: cssVar('blur.md'),
        lg: cssVar('blur.lg'),
        xl: cssVar('blur.xl'),
    },
    borderWidth: {
        none: cssVar('borderWidth.none'),
        thin: cssVar('borderWidth.thin'),
        default: cssVar('borderWidth.default'),
        thick: cssVar('borderWidth.thick'),
        heavy: cssVar('borderWidth.heavy'),
    },
} as const

export type ThemeTokens = typeof themeTokens
