export type { IconType } from 'react-icons'

export {
    MdArrowDownward as IconArrowDown,
    MdArrowUpward as IconArrowUp,
    MdArrowBack as IconArrowLeft,
    MdArrowForward as IconArrowRight,
    MdKeyboardArrowDown as IconChevronDown,
    MdKeyboardArrowUp as IconChevronUp,
    MdKeyboardArrowLeft as IconChevronLeft,
    MdKeyboardArrowRight as IconChevronRight,
    MdClose as IconClose,
    MdCheck as IconCheck,
    MdSearch as IconSearch,
    MdCalendarToday as IconCalendar,
    MdWbSunny as IconSun,
    MdNightlight as IconMoon,
    MdInfo as IconInfo,
    MdWarning as IconWarning,
    MdError as IconError,
    MdCheckCircle as IconSuccess,
    MdFormatBold as IconBold,
    MdFormatItalic as IconItalic,
    MdFormatUnderlined as IconUnderline,
    MdAdd as IconPlus,
    MdRemove as IconMinus,
    MdMoreHoriz as IconMoreHorizontal,
    MdMoreVert as IconMoreVertical,
    MdVisibility as IconEye,
    MdVisibilityOff as IconEyeOff,
} from 'react-icons/md'
